name: Development

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:       # 手动触发
  push:
    branches:
      - 'feature/**'       # 匹配所有以 feature/ 开头的分支

jobs:
  Development-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 18
      - uses: skiddph/actions-env@v1.0.2
      - run: npm install
      - run: node server.js

      # 检查文件是否生成成功
      - name: Check generated file
        run: |
          if [ -f "./lighthouse-dark-report.html" ]; then
            echo "Lighthouse report generated successfully"
            ls -la lighthouse-dark-report.html
          else
            echo "Error: lighthouse-dark-report.html not found"
            exit 1
          fi

      - uses: wlixcc/SFTP-Deploy-Action@v1.0 
        with:  
          username: 'ubuntu'
          server: '${{ secrets.SERVER_IP }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './lighthouse-dark-report.html'  # 注意：你的脚本生成的是这个文件名
          remote_path: '/home/ubuntu/lighthouse/'      # 注意：末尾加斜杠表示目录
